spring:
  profiles:
    active: dev

---
server:
  port: 8888

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/challenge?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
        cache: DEBUG
---

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!

  config:
    activate:
      on-profile: prod

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    #show-sql: true
    database: mysql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG